// Generated by gencpp from file bike_core/pid_params_msg.msg
// DO NOT EDIT!


#ifndef BIKE_CORE_MESSAGE_PID_PARAMS_MSG_H
#define BIKE_CORE_MESSAGE_PID_PARAMS_MSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace bike_core
{
template <class ContainerAllocator>
struct pid_params_msg_
{
  typedef pid_params_msg_<ContainerAllocator> Type;

  pid_params_msg_()
    : header()
    , p(0.0)
    , i(0.0)
    , d(0.0)
    , output_limit(0.0)
    , integrval_limit(0.0)  {
    }
  pid_params_msg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , p(0.0)
    , i(0.0)
    , d(0.0)
    , output_limit(0.0)
    , integrval_limit(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _p_type;
  _p_type p;

   typedef float _i_type;
  _i_type i;

   typedef float _d_type;
  _d_type d;

   typedef float _output_limit_type;
  _output_limit_type output_limit;

   typedef float _integrval_limit_type;
  _integrval_limit_type integrval_limit;





  typedef boost::shared_ptr< ::bike_core::pid_params_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bike_core::pid_params_msg_<ContainerAllocator> const> ConstPtr;

}; // struct pid_params_msg_

typedef ::bike_core::pid_params_msg_<std::allocator<void> > pid_params_msg;

typedef boost::shared_ptr< ::bike_core::pid_params_msg > pid_params_msgPtr;
typedef boost::shared_ptr< ::bike_core::pid_params_msg const> pid_params_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bike_core::pid_params_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bike_core::pid_params_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bike_core::pid_params_msg_<ContainerAllocator1> & lhs, const ::bike_core::pid_params_msg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.p == rhs.p &&
    lhs.i == rhs.i &&
    lhs.d == rhs.d &&
    lhs.output_limit == rhs.output_limit &&
    lhs.integrval_limit == rhs.integrval_limit;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bike_core::pid_params_msg_<ContainerAllocator1> & lhs, const ::bike_core::pid_params_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bike_core

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bike_core::pid_params_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bike_core::pid_params_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bike_core::pid_params_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bike_core::pid_params_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bike_core::pid_params_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bike_core::pid_params_msg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bike_core::pid_params_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "09e72efa8cdc37046481768f9ac21d94";
  }

  static const char* value(const ::bike_core::pid_params_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x09e72efa8cdc3704ULL;
  static const uint64_t static_value2 = 0x6481768f9ac21d94ULL;
};

template<class ContainerAllocator>
struct DataType< ::bike_core::pid_params_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bike_core/pid_params_msg";
  }

  static const char* value(const ::bike_core::pid_params_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bike_core::pid_params_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"float32 p\n"
"float32 i\n"
"float32 d\n"
"float32 output_limit\n"
"float32 integrval_limit\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::bike_core::pid_params_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bike_core::pid_params_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.p);
      stream.next(m.i);
      stream.next(m.d);
      stream.next(m.output_limit);
      stream.next(m.integrval_limit);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pid_params_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bike_core::pid_params_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bike_core::pid_params_msg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "p: ";
    Printer<float>::stream(s, indent + "  ", v.p);
    s << indent << "i: ";
    Printer<float>::stream(s, indent + "  ", v.i);
    s << indent << "d: ";
    Printer<float>::stream(s, indent + "  ", v.d);
    s << indent << "output_limit: ";
    Printer<float>::stream(s, indent + "  ", v.output_limit);
    s << indent << "integrval_limit: ";
    Printer<float>::stream(s, indent + "  ", v.integrval_limit);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BIKE_CORE_MESSAGE_PID_PARAMS_MSG_H
