// Generated by gencpp from file bike_core/sbus_channels_msg.msg
// DO NOT EDIT!


#ifndef BIKE_CORE_MESSAGE_SBUS_CHANNELS_MSG_H
#define BIKE_CORE_MESSAGE_SBUS_CHANNELS_MSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace bike_core
{
template <class ContainerAllocator>
struct sbus_channels_msg_
{
  typedef sbus_channels_msg_<ContainerAllocator> Type;

  sbus_channels_msg_()
    : header()
    , channels_value()  {
      channels_value.assign(0);
  }
  sbus_channels_msg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , channels_value()  {
  (void)_alloc;
      channels_value.assign(0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<uint16_t, 16>  _channels_value_type;
  _channels_value_type channels_value;





  typedef boost::shared_ptr< ::bike_core::sbus_channels_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bike_core::sbus_channels_msg_<ContainerAllocator> const> ConstPtr;

}; // struct sbus_channels_msg_

typedef ::bike_core::sbus_channels_msg_<std::allocator<void> > sbus_channels_msg;

typedef boost::shared_ptr< ::bike_core::sbus_channels_msg > sbus_channels_msgPtr;
typedef boost::shared_ptr< ::bike_core::sbus_channels_msg const> sbus_channels_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bike_core::sbus_channels_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bike_core::sbus_channels_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bike_core::sbus_channels_msg_<ContainerAllocator1> & lhs, const ::bike_core::sbus_channels_msg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.channels_value == rhs.channels_value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bike_core::sbus_channels_msg_<ContainerAllocator1> & lhs, const ::bike_core::sbus_channels_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bike_core

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bike_core::sbus_channels_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bike_core::sbus_channels_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bike_core::sbus_channels_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bike_core::sbus_channels_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bike_core::sbus_channels_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bike_core::sbus_channels_msg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bike_core::sbus_channels_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2e090f1a68ca526969f62f98dbfe335b";
  }

  static const char* value(const ::bike_core::sbus_channels_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2e090f1a68ca5269ULL;
  static const uint64_t static_value2 = 0x69f62f98dbfe335bULL;
};

template<class ContainerAllocator>
struct DataType< ::bike_core::sbus_channels_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bike_core/sbus_channels_msg";
  }

  static const char* value(const ::bike_core::sbus_channels_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bike_core::sbus_channels_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"uint16[16] channels_value\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::bike_core::sbus_channels_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bike_core::sbus_channels_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.channels_value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sbus_channels_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bike_core::sbus_channels_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bike_core::sbus_channels_msg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "channels_value[]" << std::endl;
    for (size_t i = 0; i < v.channels_value.size(); ++i)
    {
      s << indent << "  channels_value[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.channels_value[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BIKE_CORE_MESSAGE_SBUS_CHANNELS_MSG_H
